#!/usr/bin/env ansible-playbook
---
- name: Preparing host to Install OpenShift 4
  hosts: localhost
  connection: local
  gather_facts: True
  vars:
    guid: "{{ ansible_env.HOSTNAME.split('.')[1] }}"
    aws_region: "us-east-2"
    aws_client: { url: "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip", filename: "awscli-bundle.zip" }
    openshift_version: "4.2.12"
    openshift_install: { url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-{{ openshift_version }}.tar.gz", filename: "openshift-install.tar.gz" }
    openshift_client: { url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-{{ openshift_version }}.tar.gz", filename: "openshift-client.tar.gz" }
    operator_version: "v0.13.0"
    operator_sdk: { url: "https://github.com/operator-framework/operator-sdk/releases/download/{{ operator_version }}/operator-sdk-{{ operator_version }}-x86_64-linux-gnu", filename: "operator-sdk" }
    operator_packages_needed: 
         - git
         - docker
         - podman
         - buildah
    go_language: { url: "https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz", filename: "golang.tar.gz" }
    go_workspace: "/root/go_workspace"
  tasks:
     - name: "Setting a default guid in case is missing"
       set_fact: guid="maltron"
       when: guid is not defined or guid is none

     - name: "Parameter: aws_key"
       fail: msg="aws_key is not defined or is empty"
       when: aws_key is not defined or aws_key is none
       tags: [ always ]

     - name: "Parameter: aws_secret"
       fail: msg="aws_secret is not defined or is empty"
       when: aws_secret is not defined or aws_secret is none
       tags: [ always ]

     - name: "Downloading Operator SDK"
       get_url: url={{ operator_sdk.url }} dest=/usr/bin/{{ operator_sdk.filename }} mode=755
       tags: [ operator ]

     - name: "Installing packages needed for Operator SDK"
       yum: name={{ operator_packages_needed }} state=latest
       tags: [ operator ]

     - name: "Starting Docker Service"
       service: name=docker state=started
       tags: [ operator ]

     - name: "Downloading files: {{ aws_client.filename }}, {{ openshift_install.filename }}, {{ openshift_client.filename }}, {{ go_language.filename }}"
       get_url: url={{ item.url }} dest=./{{ item.filename }}
       with_items: 
           - "{{ aws_client }}"
           - "{{ openshift_install }}"
           - "{{ openshift_client }}"
           - "{{ go_language }}"

     - name: "Unarchiving files: {{ aws_client.filename }}, {{ openshift_install.filename }}, {{ openshift_client.filename }}"
       unarchive: src={{ item.filename }} dest=.
       with_items: 
           - "{{ aws_client }}"
           - "{{ openshift_install }}"
           - "{{ openshift_client }}"

     - name: "Unarchiving Go Language into /usr/bin"
       unarchive: src={{ go_language.filename }} dest=/usr/bin

     - name: "Creating a Go workspace for all Go projects: {{ go_workspace }}"
       file: path={{ go_workspace }} state=directory

     - name: "Creating a Operators directory within Go workspace: {{ go_workspace }}/src/github.com"
       file: path={{ go_workspace }}/src/github.com state=directory

     - name: "Move files: oc, kubectl, openshift-install to /usr/bin"
       copy: src={{ item }} dest=/usr/bin mode=755
       with_items: 
           - "oc"
           - "kubectl"
           - "openshift-install"

     - name: "Setup Bash completion for the OpenShift command line utility"
       command: oc completion bash
       register: oc_completion_bash

     - name: "Insert the content from <oc completion bash> into /etc/bash_completion.d/openshift"
       lineinfile: path=/etc/bash_completion.d/openshift insertafter=EOF line={{ oc_completion_bash.stdout }} create=true

     - name: "Creating directory: /root/cluster-{{ guid }}"
       file: path=/root/cluster-{{ guid }} state=directory

     - name: "AWS: Installing Client" 
       command: ./awscli-bundle/install -i /usr/local/aws -b /bin/aws

     - name: "AWS: Creating Client configuration directory: /root/.aws"
       file: path=/root/.aws state=directory

     - name: "AWS: Generating AWS Client configuration: /root/.aws/credentials"
       template: src=templates/aws_config.j2 dest=/root/.aws/credentials force=True

     - name: "Generating SSH Public and Private Keys"
       command: "ssh-keygen -b 4096 -t rsa -f /root/.ssh/cluster-{{ guid }}-key -q -N \"\""

     - name: "Creating a environment variables on /root/.bashrc"
       lineinfile: path=/root/.bashrc insertafter=EOF line="export {{ item }}"
       with_items: 
           - "GUID={{ guid }}"
           - "KUBECONFIG=/root/cluster-{{ guid }}/auth/kubeconfig"
           - "GOPATH={{ go_workspace }}"
           - "GOROOT=/usr/bin/go"
           - "GO111MODULE=on"
           - "PATH=${PATH}:$GOROOT/bin:${GOPATH}"

     - name: Cleaning
       file: path={{ item }} state=absent
       with_items:
           - oc
           - kubectl
           - openshift-install
           - awscli-bundle
           - "{{ aws_client.filename }}"
           - "{{ openshift_install.filename }}"
           - "{{ openshift_client.filename }}"
           - "{{ go_language.filename }}"

     - debug: msg="openshift-install create cluster --dir /root/cluster-{{ guid }} --log-level=debug"
